config/routes.rb
Rails.application.routes.draw do
  resources :follows
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  delete '/users/sign_out' => 'sessions#destroy'
  get '/user/home' => 'users#show'


  resources :users

  resources :articles do
    resources :comments
end



  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, :optional => true

  has_many :comments
  # , dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :body, presence: true, allow_blank: false
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

   validates :follower_id, uniqueness: { scope: :followee_id }
   validates :followee_id, uniqueness: { scope: :follower_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles

    has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
   has_many :followees, through: :followed_users
   has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
   has_many :followers, through: :following_users

   has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def fetch_user
    @current_user = User.find_by :id => session[:id] if session[:id].present?
    session[:id] = nil unless @current_user.present?
  end

  def check_for_login # checks if somebody is logged in - place in controller where you need to be logged into access
  redirect_to user_session_path unless current_user.present?
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :blog_title, :about_me, :followee_id, :follower_id, :followees, :followers])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_for_login

  def new
    @article = Article.new
  end

  def create
    article = Article.create article_params
      current_user.articles << article
      flash[:notice] = "Article created"
    redirect_to article_path(article.id)
  end

  def index
  end

  def show
    @article = Article.find params[:id]
    @comment = Comment.new(:article => @article)
  end

  def edit
    @article = Article.find params[:id]
  end

  def update
    article = Article.find params[:id]
    article.update article_params
    redirect_to article
  end

  def destroy
      article = Article.find params[:id]
        if (@current_user.id) == article.user_id
          article.comments.destroy_all
          article.destroy
        end
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :topic, :body, :image, :user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_for_login, except: [:index]

  def index
    @comments = @article.comments.order(created_at: :desc)
  end

  def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.new(comment_params)
      @comment.user = current_user
        if @comment.save
          flash[:notice] = 'Comment was successfully created.'
        else
          flash[:notice] = "Error creating comment: #{@comment.errors}"
        end
    redirect_to(@comment.article)
  end

  def destroy
      @article = Article.find params[:article_id]
      @comment = @article.comments.find(params[:id])
        if @comment.user_id == @current_user.id
          @comment.destroy
        else
          flash[:notice] = "Comment not owned by user"
        end
      redirect_to(@comment.article)
  end

private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user
  end

  def show
    @article = Article.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
   @user = User.find(params[:id])
   @email = @user.email
  end

  def follow
    @user = User.find(params[:id])
    current_user.followees << @user
    redirect_back(fallback_location: user_path(@user))
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followee_id: @user.id).destroy
    redirect_back(fallback_location: user_path(@user))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/articles/_form.html.erb
<div class="form-group">
  <%= form_for @article do |f| %>
    <%= f.label :title %>
      <%= f.text_field :title, :required => true, :autofocus => true, :class => "form-control", :id => "exampleFormControlInput1" %>

    <%= f.label :topic %>
      <%= f.text_field :topic, :required => true, :class => "form-control", :id => "exampleFormControlInput1" %>

    <%= f.label :body %>
      <%= f.text_field :body, :required => true, :class => "form-control form-control-lg", :id => "exampleFormControlTextarea1"  %>

    <%= f.label :image %>
      <%= f.url_field :image, :class => "form-control", :id => "exampleFormControlInput1" %>

    <%= f.submit :class => "btn btn-success mt-4 px-2"%>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h2>Edit Article</h2>
  <%= render :partial => 'form' %>

app/views/articles/index.html.erb
<h1 class="px-2 mb-5 mt-2"><a href="#">Informative.</a></h1>
<div class="container ">
  <div class="card-columns">
    <% if current_user.followees.present? %>
      <% current_user.followees.each do |user| %>
        <% user.articles.each do |article| %>
          <div class="card border-none">
              <div class="col-mb-4 p-2">
                <%= image_tag article.image, :class => "feed-img card-img-top text-center" if article.image.present?%>
                <h4 class="h4 card-title pb-4">
                  <%= link_to "#{article.title}", article%>
                </h4>
                <p class="h6 card-text pb-2">
                  <%= truncate "#{article.body}", length: 75 %>
                </p>
                <p class="h6 card-text">
                  By <%= link_to "#{article.user.username}", user_path(article.user.id)%>
                </p>
                <p class="h6 card-text">
                  <%= "#{article.created_at.strftime("%b %d, %Y")}" %>
                </p>
              </div>
            </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<h2>New Article</h2>
  <%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div class="container">
  <div class="mb-3">
    <h1><%= @article.title %></h1>
    By <h6 class="font-weight-bold"><%= link_to @article.user.username, user_path(@article.user.id) %></h6>
    <div>
      <h6><%= @article.topic %></h6>
      <p><%= @article.created_at.strftime("%b %d, %Y") %></p>
    </div>
  </div>
  <div class="row p-3">
    <%= image_tag @article.image, :class => ' feature mb-3', :alt => @article.title if @article.image.present?%>
    <p><%= @article.body %></p>
    <div class="controls">
      <div class="d-inline-block">
        <%= link_to "Edit", edit_article_path(@article), :class => " btn btn-dark"%>
      </div>
      <div class="d-inline-block">
        <%= link_to "Delete", @article, :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>
  <div class="comment-container mt-3">
    <div class="row d-flex ">
      <div class="col-lg-6">
        <%= render :partial => 'comments/comment' %>
        <%= render 'comments/form' %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<h4 class="mt-2">Latest Comments</h4>

  <% @article.comments.each do |comment| %>
    <div class="d-flex flex-row px-2">
      <div class="w-100">
        <h6 class="h6 font-medium"><%= link_to "#{comment.user.username}", user_path(comment.user.id) %></h6>
        <span class=""><%= comment.body %> </span>
        <div class="comment-footer">
          <span class="d-flex justify-content-end">
            <%= link_to 'Delete', article_comment_path(@article, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "mb-2 btn btn-sm btn-outline-secondary" %>
          </span>
          <span class="text-muted d-flex justify-content-end">
            <%= "#{comment.created_at.strftime("%b %d, %Y")}" %>
          </span>
        </div>
      </div>
    </div>
  <% end %>

app/views/comments/_form.html.erb
<div class="form-group yield-container mt-2">
  <h5 class="h5 mt-2">Add A Comment</h5>

  <%= form_for [ @article, @comment ] do |f| %>
    <p class=" p container">
      <%= f.label "text" %>
      <%= f.text_field :body, :required => true, :class => "px-0 form-control exampleFormControlInput1" %>
    </p>
    <span class="d-flex justify-content-end mr-2">
      <%= f.submit :class => "btn btn-success mr-2 px-2"%>
    </span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@200&family=Playfair+Display:wght@600&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <% if current_user.present? %>
          <ul class="navbar-nav mr-auto mb-2 mt-0.5">
            <li class="nav-item m-1">
              <%= link_to "Feed", articles_path, :class=>" btn btn-outline-light" %>
            </li>
            <li class="nav-item m-1">
              <%= link_to "Home", user_path(current_user), :class=>"btn btn-outline-light" %>
            </li>
            <li class="nav-item dropdown m-1">
              <%= link_to "Article", articles_path, {:class=>"dropdown-toggle btn btn-outline-light", :id => "navbarDropdownMenuLink ", 'role'=>"button", 'data-toggle'=>"dropdown", 'aria-haspopup'=>"true", 'aria-expanded'=>"false"}%>
                <div class="dropdown-menu">
                  <%= link_to "New Article", new_article_path, :class=>" dropdown-item btn btn-outline-light" %>
                  <%= link_to "All Articles", root_path, :class=>" dropdown-item btn btn-outline-light" %>
                </div>
            </li>
            <li class="nav-item m-1">
              <%= link_to "Account Preferences", edit_user_registration_path,:class=>"btn btn-outline-light" %>
            </li>
            <li class="nav-item m-1">
              <%= link_to "Sign Out", destroy_user_session_path, :method => 'delete', :class=>"btn btn-outline-light" %>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav mr-auto mb-2 mt-0.5">
            <li class="nav-item m-1">
              <%= link_to "All Articles", root_path, :class=>"btn btn-outline-light" %>
            </li>
            <li class="nav-item m-1">
              <%= link_to "Sign in", new_user_session_path, :class=>"btn btn-outline-light" %>
            </li>
            <li class="nav-item m-1">
              <%= link_to "Sign Up", new_user_registration_path, :class=>"btn btn-outline-light"%>
            </li>
          </ul>
        <% end %>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
        <div class="yield-container">
          <%= yield %>
        </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<body class="home">

  <div class="container">
    <div class="mb-2 mt-2">
      <p class="h1">Welcome to Informative.
      </p>
      <p class="h6">An open article sharing platform where users can share their voice on any topic, access dynamic content and connect with people with shared interests.</p>

      <% if current_user.present? %>
        <p class="h6">You are currently logged in as <strong><%= current_user.email %></strong></p>
      <% end %>
    </div>
  </div>
  <div class="container-box">
    <div class="card-columns p-2 mt-3">
      <%  Article.all.order("created_at DESC").each do |article| %>
        <div class="col mb-4">
          <div class="card border-none p-2">
            <%= image_tag article.image, :class => "card feed-img centre" if article.image.present?%>
            <p class="h4 pb-2"><%= link_to "#{article.title}", article%></p>
            <p class="h6 pb-4"><%= truncate "#{article.body}", length: 75 %></p>
            <p class="h6">By <%= link_to "#{article.user.username}", user_path(article.user.id)%></p>
            <p class="h6">Posted<%= " #{article.created_at.strftime("%b %d, %Y")}" %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/users/new.html.erb
<h2>New Article</h2>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h1><a href="#" class="blog-header-logo text-dark center"> <%= "#{@user.blog_title}" %></a></h1>
  <h3 class="text-dark"><%= "#{@user.about_me}" %></h3>

    <% if current_user.followees.include?(@user) %>
      <h6 class="mt-5 mb-2 mr-5 d-flex justify-content-end" ><%= button_to "Unfollow", unfollow_user_path, method: "POST", :class => "btn btn-outline-secondary strong" %></h6>
    <% else %>
      <h6 class="mt-5 mb-2 mr-5 d-flex justify-content-end"><%= button_to "Follow", follow_user_path, method: "POST", :class => "btn btn-outline-secondary strong"  %></h6>
    <% end%>

<div class="container">
  <div class="card-columns p-2 mt-2">
    <% @user.articles.each do |article|%>
      <div class="card border-none p-2">
        <%= image_tag article.image, :class => " eed-img card-img-top text-center" if article.image.present?%>
        <h4 class="h4 pb-2"><%= link_to "#{article.title}", article%></h4>
        <p class="h6 pb-4"><%= truncate "#{article.body}", length: 100 %></p>
        <p class="h6">Published:  <%= "#{article.created_at.strftime("%b %d, %Y")}" %> </p>
      </div>
    <% end %>
  </div>
</div>

<h6 class="h6"><%= @user.followers.count if @user.followers.present?%> subscribers.</h6>